<a href="https://colab.research.google.com/github/vldslt/GBLINALG/blob/main/linalg5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.decomposition import PCA

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [47]:
m = np.array([[1, 2, 0],
     [0, 0, 5],
     [3, -4, 2],
     [1, 6, 5],
     [0, 1, 0]])

In [48]:
U, S, W = np.linalg.svd(m)
print(f'U = \n{U}')
print(f'S = \n{S}')
print(f'V = \n{W.T}')

U = 
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
S = 
[8.82 6.14 2.53]
V = 
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [49]:
np.dot(U, U.T)

array([[ 1.,  0., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [-0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1., -0.],
       [-0.,  0.,  0., -0.,  1.]])

In [50]:
np.dot(V, V.T)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [51]:
np.linalg.norm(m, ord=2)

8.824868854820444

In [56]:
D = np.zeros_like(m, dtype=float)
D[np.diag_indices(min(m.shape))] = S
print(D[0,0])

8.824868854820442


In [28]:
np.linalg.norm(m)

11.045361017187261