<a href="https://colab.research.google.com/github/vldslt/GBLINALG/blob/main/linalg4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

вычитаем из 3 строки 1

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
0 & 0 & -4 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
умножаем 1 строку на 2 и вычитаем её из 2 сторки

$$\begin{pmatrix}
\left.\begin{matrix}
2 & 2 & -2 & -2\\ 
0 & -1 & 3 & 3\\ 
0 & 0 & -4 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
делим 1 строку на 2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -1\\ 
0 & -1 & 3 & 3\\ 
0 & 0 & -4 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
делим 3 строку на 4

$$\begin{cases}
x_{1}+x_{2}-x_{3}-x_{4}=0, \\
-x_{2}+3x_{3}+3x_{4}=-2, \\
-x_{3}+0,25x_{4}=1.
\end{cases} => $$
$$\begin{cases}
x_{1}+x_{2}-x_{3}-x_{4}=0, \\
-x_{2}+3x_{3}+3x_{4}=-2, \\
x_{3}=0,25x_{4}-1.
\end{cases} =>$$ 
$$\begin{cases}
x_{1}+x_{2}-x_{3}-x_{4}=0, \\
-x_{2}+0.75x_{4}-3+3x_{4}=-2, \\
x_{3}=0,25x_{4}-1.
\end{cases}=>$$
$$\begin{cases}
x_{1}+x_{2} =x_{3}+x_{4}, \\
x_{2}=3.75x_{4}-1, \\
x_{3}=0,25x_{4}-1.
\end{cases}
$$
$$\begin{cases}
x_{1}+2.5x_{4}=0, \\
x_{2}=3.75x_{4}-1, \\
x_{3}=0,25x_{4}-1.
\end{cases}
$$
$$\begin{cases}
x_{1}=-2.5x_{4}, \\
x_{2}=3.75x_{4}-1, \\
x_{3}=0,25x_{4}-1.
\end{cases}
$$
$$\begin{cases}
-2.5x_{4}+3.75x_{4}-0.25x_{4}+1-x_{4}=0 => x_{4}=x_{4}+1  !!! \\
x_{1}=-2.5x_{4}, \\
x_{2}=3.75x_{4}-1, \\
x_{3}=0,25x_{4}-1.
\end{cases}
$$

Полученное равенство не имеет смысла, а значит, система решений не имеет.

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$
вычитаем 3 строку из первой, после вычитаем получившуюся первую строку из 2 строки

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -2 & 2\\ 
0 & -3 & -5\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-21\\
0
\end{matrix}
\end{pmatrix}$$
умножаем 3 строку на 2 и прибавляем получившееся к 1 строке

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
4 & 0 & 0\\ 
0 & -3 & -5\\ 
2 & 2 & -2
\end{matrix}\right|
\begin{matrix}
4\\ 
-21\\
0
\end{matrix}
\end{pmatrix}$$

$\begin{cases}
4x_{1}=4, \\
-3x_{2}-5x_{3}=-21, \\
2x_{1}+2x_{2}-2x_{3}=0;\end{cases} = > $\begin{cases}
x_{1}=1, \\
x_{3}=4, \\
x_{2}=x_{3}-1 = 3;
\end{cases}

система совместна

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$
складываем 2 и 1 строки, вычитаем получившуюся 2 строку из 3, делим получившуюся 3 строку на 6, ко 2 строке прибавляем 1 строку, делим вторую строку на 5

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
0 & -2 & 0
\end{matrix}\right|
\begin{matrix}
1\\ 
0\\
1
\end{matrix}
\end{pmatrix}$$

$\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=0, \\
-2x_{2}=1;
\end{cases} =>$\begin{cases}
6x_{3}=1+2-2+6x_{3}=>6x_{3} = 6x_{3}+1, \\
x_{1}=-1-3x_{3}=0, \\
x_{2}=0,5;
\end{cases}

Полученное равенство не имеет смысла, а значит, система решений не имеет, система не совместна

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8\\
\end{matrix}\right|
\begin{matrix}
4\\ 
-2\\
\end{matrix}
\end{pmatrix}$$
умножаем 2 строку на 2, прибавляем к 2 строке 1 строку

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
7 & 4 & -11\\
\end{matrix}\right|
\begin{matrix}
4\\ 
0\\
\end{matrix}
\end{pmatrix}$$

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
7x_{1}+4x_{2}-11x_{3}=0. 
\end{cases}$
в) $\begin{cases}
x_{2} = 2-0.5x_{1}-2.5x_{3}, \\
x_{1} = 11x_{3}-4x_{2} 
\end{cases}$
$\begin{cases}
x_{2} = 2-0.5x_{1}-2.5x_{3}, \\
x_{1} = 11x_{3}-2x_{1}-10x_{3} 
\end{cases}$
$\begin{cases}
x_{2} = 2-8x_{1}\\
x_{3} = 3x_{1} 
\end{cases}$
$\begin{cases}
x_{1}+4-16x_{1}+15x_{1}=4 =>4=4, \\
-42x_{1}=-8 => x_{1} = 5.25
\end{cases}$
$\begin{cases}
x_{2} = 2-8x_{1} = -40\\
x_{3} = 3x_{1} = 15.75\end{cases}$

система совместна

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [ ]:
import numpy as np
matA = np.array([[1, 3, -2, 4], 
                   [0, 5, 0, 1], 
                   [0, 0, 3, 0],
                   [0, 0, 0, 2]])
matB = np.array([
                 3,
                 2,
                 4,
                 1])

In [96]:
def SwapRows(A, B, row1, row2):
    A[row1], A[row2] = A[row2], A[row1]
    B[row1], B[row2] = B[row2], B[row1]
def DivideRow(A, B, row, divider):
    A[row] = [a / divider for a in A[row]]
    B[row] /= divider
def CombineRows(A, B, row, source_row, weight):
    A[row] = [(a + k * weight) for a, k in zip(A[row], A[source_row])]
    B[row] += B[source_row] * weight
def Gauss(A, B):
    column = 0
    while (column < len(B)):
        current_row = None
        for r in range(column, len(A)):
            if current_row is None or abs(A[r][column]) > abs(A[current_row][column]):
                 current_row = r
        if current_row is None:
            return None
        if current_row != column:
            SwapRows(A, B, current_row, column)
        DivideRow(A, B, column, A[column][column])
        for r in range(column + 1, len(A)):
            CombineRows(A, B, r, column, -A[r][column])
        column += 1
    X = [0 for b in B]
    for i in range(len(B) - 1, -1, -1):
        X[i] = B[i] - sum(x * a for x, a in zip(X[(i + 1):], A[i][(i + 1):]))
    return X

Gauss(matA, matB)

[5, 0, 1, 0]

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & 4
\end{vmatrix}=2$$
$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4 
\end{vmatrix}=10$$

$$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7 
\end{vmatrix}=4$$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=43$$
$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=-43$$
$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=43$$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [ ]:
def cholesky_reduce(A):
    pivot = A[0, 0]
    b = np.mat(A[1:, 0])
    B = A[1:, 1:]
    return B - (b.T * b) / pivot


def L(A):
    n = A.shape[0]
    if n == 1:
        return np.sqrt(A)
    b = np.mat(A[1:, 0])
    pivot = np.sqrt(A[0, 0])
    return np.bmat([
        [np.mat(pivot), np.zeros((1, n - 1))],
        [b.T / pivot, L(cholesky_reduce(A))]
    ])


def __main():
    A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
    print(L(A))

if __name__ == '__main__':
    __main()

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.